title: Space - A Portal Story
email: spaceaps@gmail.com
description: >- 
  The official site for Space - A Portal Story, an upcoming community made portal game.
github_username:  ranchordo

theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
