title: Space - A Portal Story
email: spaceaps@gmail.com
description: >- 
  The official site for Space - A Portal Story, an upcoming community made portal game.
baseurl: "/space-a-portal-story" # the subpath of your site, e.g. /blog
url: "https://ranchordo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ranchordo

# Build settings
theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache
